(function(g){var window=this;var Xua=function(a,b){var c=[];g.pm(b,function(a){var b;try{b=g.$D.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.ZD(b)&&c.push(a):c.push(a)},a);
return c},Yua=function(a,b){var c=Xua(a,b);
(0,g.H)(c,function(a){g.$D.prototype.remove.call(this,a)},a)},o9=function(a,b){g.BW.call(this,g.U("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.B=!1;this.G={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},Zua=function(a){return a.H?a.F+((0,g.F)()-a.A)/1E3:a.F},$ua=function(){var a=g.BH;
Yua(a,a.g.Nd(!0))},p9=function(a){g.dI.call(this,"ScreenServiceProxy");
this.Uc=a;this.o=[];this.o.push(this.Uc.$_s("screenChange",(0,g.A)(this.bQ,this)));this.o.push(this.Uc.$_s("onlineScreenChange",(0,g.A)(this.wM,this)))},q9=function(a){g.RH("cloudview",a)},ava=function(a){q9("setApiReady_ "+a);
g.u("yt.mdx.remote.cloudview.apiReady_",a,void 0)},r9=function(){return g.x("yt.mdx.remote.cloudview.instance_")},bva=function(a){g.VG[a]&&(a=g.VG[a],(0,g.H)(a,function(a){g.TG[a]&&delete g.TG[a]}),a.length=0)},s9=function(){return g.x("yt.mdx.remote.connection_")},t9=function(a){g.u("yt.mdx.remote.connectData_",a,void 0)},cva=function(a){g.u("yt.mdx.remote.currentScreenId_",a,void 0)},u9=function(){return g.x("yt.mdx.remote.currentScreenId_")},w9=function(){if(!v9){var a=g.x("yt.mdx.remote.screenService_");
v9=a?new p9(a):null}return v9},x9=function(a){g.u("yt.mdx.remote.cloudview.initializing_",a,void 0)},y9=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},z9=function(a){q9("setCastInstalled_ "+a);
g.DH("yt-remote-cast-installed",a)},A9=function(a){g.RH("cloudview",a)},dva=function(a,b){r9().init(a,b)},B9=function(){return!!g.EH("yt-remote-cast-installed")},eva=function(){q9("dispose");
var a=r9();a&&a.dispose();g.u("yt.mdx.remote.cloudview.instance_",null,void 0);ava(!1);(0,g.o2)(C9);C9.length=0},fva=function(){var a=window.document.createElement("a");
g.Rd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Ta(a)},gva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},hva=function(a){var b=g.SG();
if(b)if(b.clear(a),a)bva(a);else for(var c in g.VG)bva(c)},D9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},F9=function(a){var b=s9();
t9(null);a||cva("");g.u("yt.mdx.remote.connection_",a,void 0);E9&&((0,g.H)(E9,function(b){b(a)}),E9.length=0);
b&&!a?g.$G("yt-remote-connection-change",!1):!b&&a&&g.$G("yt-remote-connection-change",!0)},iva=function(){return g.x("yt.mdx.remote.connectData_")},G9=function(){var a=u9();
if(!a)return null;var b=w9().Sd();return g.cI(b,a)},jva=function(a,b){z9(!0);
x9(!1);dva(a,function(a){a?(ava(!0),g.ZG("yt-remote-cast2-api-ready")):(A9("Failed to initialize cast API."),z9(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),eva());b(a)})},kva=function(){return B9()?r9()?r9().getCastSession():(A9("getCastSelector: Cast is not initialized."),null):(A9("getCastSelector: Cast API is not installed!"),null)},lva=function(){var a=fva(),b=window.document.getElementById(a),c=b&&g.RF(b,"loaded");
c||b&&!c||(b=gva(a,function(){g.RF(b,"loaded")||(g.SF(b,"loaded","true"),g.ZG(a),g.kF(g.ya(hva,a),0))}))},mva=function(a){return(0,g.J)(a,function(a){return{key:a.id,
name:a.name}})},nva=function(){if(g.qoa){var a=2,b=g.Gh(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Lh("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ih,c)}},I9=function(a,b){u9();
G9()&&G9();cva(a.id);var c=new g.hJ(H9,a,D9());c.connect(b,iva());c.subscribe("beforeDisconnect",function(a){g.$G("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){s9()&&(s9(),F9(null))});
F9(c)},J9=function(){var a=g.iI();
if(!a)return null;var b=w9().Sd();return g.cI(b,a)},K9=function(a){g.RH("remote",a)},L9=function(){var a=s9();
return!!a&&3!=a.getProxyState()},M9=function(){y9()?r9().stopSession():A9("stopSession called before API ready.");
var a=s9();a&&(a.disconnect(1),F9(null))},ova=function(){var a;
a=w9().Uc.$_gos();var b=G9();b&&s9()&&(g.bI(a,b)||a.push(b));return mva(a)},O9=function(a,b){g.uG.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.nC;this.A=this.o=null;this.H=(0,g.A)(this.HK,this);this.F=(0,g.A)(this.Bk,this);this.G=(0,g.A)(this.GK,this);this.J=(0,g.A)(this.UK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ns,this),pva(this))):c=3;0!=c&&(b?this.Ns(c):g.kF((0,g.A)(function(){this.Ns(c)},this),0));
var d=kva();d&&N9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},P9=function(a){return new g.XI(a.B.getPlayerContextData())},qva=function(a,b,c,d,e){var f=P9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.aJ(f,b,d);g.t(c)&&(g.ZI(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);Q9(a,"setPlaylist",l);e||R9(a,f)},pva=function(a){(0,g.H)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.QM,a),this))},a)},rva=function(a){(0,g.H)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},S9=function(a,b){50>a.C.Dc()&&g.pC(a.C,b)},T9=function(a,b,c){var d=P9(a);
g.ZI(d,c);-1E3!=d.g&&(d.g=b);R9(a,d)},Q9=function(a,b,c){a.B.sendMessage(b,c)},R9=function(a,b){rva(a);
a.B.setPlayerContextData(g.bJ(b));pva(a)},N9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Bk(null));
a.A=b;a.A&&(U9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Bk(a.A.media[0]))},sva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=P9(a);b.contentId!=d.videoId&&U9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.ZI(d,a.o.getEstimatedTime());R9(a,d)}else U9("No cast media video. Ignoring state update.")},U9=function(a){g.RH("CP",a)},V9=function(a,b,c){return(0,g.A)(function(a){this.bc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.bc("Retrying "+b+" using MDx browser channel."),Q9(this,b,c))},a)},tva=function(a){var b=!1;
r9()||(a=new g.RI(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.DH("yt-remote-cast-available",a);g.$G("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){q9("onReceiverSelected: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a);g.$G("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){q9("onReceiverResumed: "+a.friendlyName);
g.DH("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){q9("onSessionChange: "+g.ZH(a));
a||g.FH("yt-remote-cast-receiver");g.$G("yt-remote-cast2-session-change",a)}),g.u("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
q9("cloudview.createSingleton_: "+b);return b},uva=function(){var a=0<=g.Gb.search(/\ (CrMo|Chrome|CriOS)\//);
return g.JG||a},W9=function(a,b){y9()?r9().setConnectedScreenStatus(a,b):A9("setConnectedScreenStatus called before ready.")},vva=function(){q9("clearCurrentReceiver");
g.FH("yt-remote-cast-receiver")},wva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){nva();a({command:"cast.sender.init"});return}}if(window.chrome)if(nva(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Eh();55<=b?a="55":50<=b&&(a="50");g.Lh("//www.gstatic.com/eureka/clank"+a+g.Jh,g.Ih)}else g.Mh(0);else g.Ih()},xva=function(a){a?(g.DH("yt-remote-session-app",a.app),g.DH("yt-remote-session-name",a.name)):(g.FH("yt-remote-session-app"),g.FH("yt-remote-session-name"));
g.u("yt.mdx.remote.channelParams_",a,void 0)},yva=function(){var a=D9();
if(g.Tb(a)){var a=g.hI(),b=g.EH("yt-remote-session-name")||"",c=g.EH("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.u("yt.mdx.remote.channelParams_",a,void 0)}},zva=function(){var a=J9();
a?(K9("Resume connection to: "+g.ZH(a)),I9(a,0)):(g.qI(),vva(),K9("Skipping connecting because no session screen found."))},Ava=function(a){K9("remote.onCastSessionChange_: "+g.ZH(a));
if(a){var b=G9();b&&b.id==a.id?W9(b.id,"YouTube TV"):(b&&M9(),I9(a,1))}else s9()&&M9()},Bva=function(){var a=ova(),b=G9();
b||(b=J9());return g.ab(a,function(a){return b&&g.WH(b,a.key)?!0:!1})},Cva=function(){var a=g.EH("yt-remote-cast-receiver");
return a?a.friendlyName:null},Dva=function(a,b,c,d){uva()?tva(b)&&(x9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?jva(a,c):(window.__onGCastApiAvailable=function(b,d){b?jva(a,c):(A9("Failed to load cast API: "+d),z9(!1),x9(!1),g.FH("yt-remote-cast-available"),g.FH("yt-remote-cast-receiver"),eva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):lva():wva())):q9("Cannot initialize because not running Chrome")},
Eva=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.zg(a)||"";b&&(this.port=":"+b);this.A=g.yg(a)||"";a=g.Gb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Sa(a,"10.0")&&(this.o=!1))},X9=function(a){g.X.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.GE()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",Y:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.bW(this,250);g.M(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);Fva(this,g.BV(a))},Fva=function(a,b){if(3==a.A.Xa()){var c;
c=g.V(b,128)?g.U("YTP_MDX_STATUS_ERROR"):b.qb()||g.V(b,4)?g.U("YTP_MDX_STATUS_PLAYING"):g.U("YTP_MDX_STATUS_CONNECTED");var d=a.A.Wc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.dW(a.g)},Y9=function(a,b,c){g.L.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.pn,this);b.addEventListener("onCaptionsTrackListChanged",this.Ry,this);b.addEventListener("captionschanged",this.Fy,this);b.addEventListener("captionssettingschanged",this.ds,this);b.addEventListener("videoplayerreset",this.Ek,this);b.addEventListener("mdxautoplaycancel",this.Bu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.fz,this);c.subscribe("remotePlayerChange",this.Dk,this);c.subscribe("remoteQueueChange",this.Ek,this);
c.subscribe("autoplayUpNext",this.Dy,this);c.subscribe("previousNextChange",this.bz,this);c.subscribe("nowAutoplaying",this.Uy,this);c.subscribe("autoplayDismissed",this.Cy,this);this.suggestion=null;this.D=new g.lK(64);this.o=new g.ou(this.pA,500,this);g.M(this,this.o);this.A=new g.ou(this.qA,1E3,this);g.M(this,this.A);this.B={};this.G=new g.ou(this.EA,1E3,this);g.M(this,this.G);this.F=new g.uk(this.UR,1E3,this);g.M(this,this.F);this.J=g.y;this.ds();this.Ek();this.Dk()},Z9=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},Gva=function(a){Z9(a,0);
a.o.stop();$9(a,new g.lK(64))},c$=function(a,b){if(a$(a)&&!a.C){var c=null;
b&&(c={style:a.W.fl()},g.ac(c,b));a.g.jA(b$(a),c);a.B=P9(a.g).o}},d$=function(a,b){var c=a.W.bf();
c?qva(a.g,b$(a),b,c.Qd(),c.listId.toString()):qva(a.g,b$(a),b);$9(a,new g.lK(1))},Hva=function(a,b){if(b){var c=a.W.Wc("captions","tracklist",{Uw:1});
c&&c.length?(a.W.Ee("captions","track",b),a.C=!1):(a.W.Zk("captions"),a.C=!0)}else a.W.Ee("captions","track",{})},a$=function(a){return P9(a.g).videoId==b$(a)},b$=function(a){return a.W.getVideoData().videoId},$9=function(a,b){a.A.stop();
var c=a.D;if(b.o!=c.o||b.g!=c.g){var d=g.V(b,2);if(d!=g.V(a.D,2)){var e=a.W;(e=g.AV(e.app,e.playerType||1))&&g.yU(e,d)}a.D=b;Iva(a.H,c,b)}},e$=function(){var a=Bva();
!a&&B9()&&Cva()&&(a={key:"cast-selector-receiver",name:Cva()});return a},Jva=function(){var a=ova();
B9()&&g.EH("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Kva=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.BH&&$ua();g.kI();H9||(H9=new Eva,g.sI()&&(H9.g="/api/loungedev"));E9||(E9=g.x("yt.mdx.remote.deferredProxies_")||[],g.u("yt.mdx.remote.deferredProxies_",E9,void 0));yva();var c=w9();if(!c){var d=new g.DI(H9);g.u("yt.mdx.remote.screenService_",d,void 0);c=w9();Dva(a,d,function(a){a?u9()&&W9(u9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.$G("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.x("yt.mdx.remote.initialized_")&&
(g.u("yt.mdx.remote.initialized_",!0,void 0),K9("Initializing: "+g.Mc(b)),f$.push(g.WG("yt-remote-cast2-availability-change",function(){g.$G("yt-remote-receiver-availability-change")})),f$.push(g.WG("yt-remote-cast2-receiver-selected",function(){t9(null);
g.$G("yt-remote-auto-connect","cast-selector-receiver")})),f$.push(g.WG("yt-remote-cast2-receiver-resumed",function(){g.$G("yt-remote-receiver-resumed","cast-selector-receiver")})),f$.push(g.WG("yt-remote-cast2-session-change",Ava)),f$.push(g.WG("yt-remote-connection-change",function(a){a?W9(u9(),"YouTube TV"):J9()||(W9(null,null),vva())})),a=D9(),b.isAuto&&(a.id+="#dial"),g.AG("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,K9(" -- with channel params: "+g.Mc(a)),
xva(a),c.start(),u9()||zva())},g$=function(){B9()?r9()?y9()?(q9("Requesting cast selector."),r9().requestSession()):(q9("Wait for cast API to be ready to request the session."),C9.push(g.WG("yt-remote-cast2-api-ready",g$))):A9("requestCastSelector: Cast is not initialized."):A9("requestCastSelector: Cast API is not installed!")},h$=function(a){g.YV.call(this,a);
this.A={key:g.aI(),name:g.U("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.lK(64);this.H=0;var b=g.uV(a).C;b&&(b=b.A&&b.A.g)&&(b=new o9(a,b),g.M(this,b));b=new X9(a);g.M(this,b);g.SV(a,b.element,5)},Iva=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.qU(c,b))},i$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)M9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.bf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Yb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.bB(),0),currentTime:a.g.getCurrentTime()}}else c=null;K9("Connecting to: "+g.Mc(b));"cast-selector-receiver"==b.key?(t9(c||null),c=c||null,y9()?r9().setLaunchParams(c):A9("setLaunchParams called before ready.")):!c&&L9()&&u9()==b.key?g.$G("yt-remote-connection-change",
!0):(M9(),t9(c||null),c=w9().Sd(),(c=g.cI(c,b.key))&&I9(c,1))}};
g.p(o9,g.BW);o9.prototype.H=function(){var a=this.W.Wc("remote","receivers");a&&1<a.length&&!this.W.Wc("remote","quickCast")?(this.G=g.Cb(a,this.F,this),g.DW(this,(0,g.J)(a,this.F)),a=this.W.Wc("remote","currentReceiver"),g.CW(this,this.F(a)),this.B||(g.Q1(this.g,this),this.B=!0)):this.B&&(g.R1(this.g,this),this.B=!1)};
o9.prototype.F=function(a){return a.key};
o9.prototype.Le=function(a){return"cast-selector-receiver"==a?g.U("YTP_MDX_CAST_SELECTOR"):this.G[a].name};
o9.prototype.gd=function(a){g.BW.prototype.gd.call(this,a);this.W.Ee("remote","currentReceiver",this.G[a]);this.g.Vb()};
g.C(p9,g.dI);g.h=p9.prototype;g.h.Sd=function(a){return this.Uc.$_gs(a)};
g.h.contains=function(a){return!!this.Uc.$_c(a)};
g.h.get=function(a){return this.Uc.$_g(a)};
g.h.start=function(){this.Uc.$_st()};
g.h.mo=function(a,b,c){this.Uc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Uc.$_r(a,b,c)};
g.h.Xn=function(a,b,c,d){this.Uc.$_un(a,b,c,d)};
g.h.P=function(){for(var a=0,b=this.o.length;a<b;++a)this.Uc.$_ubk(this.o[a]);this.o.length=0;this.Uc=null;p9.O.P.call(this)};
g.h.bQ=function(){this.U("screenChange")};
g.h.wM=function(){this.U("onlineScreenChange")};
var v9=null,C9=[],E9=null,H9=null;g.C(O9,g.uG);g.h=O9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,V9(this,"play")):Q9(this,"play"),T9(this,1,g.$I(P9(this))),this.U("remotePlayerChange")):S9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,V9(this,"pause")):Q9(this,"pause"),T9(this,2,g.$I(P9(this))),this.U("remotePlayerChange")):S9(this,this.pause)};
g.h.PA=function(a){if(1==this.g){if(this.o){var b=P9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.qb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,V9(this,"seekTo",{newTime:a}))}else Q9(this,"seekTo",{newTime:a});T9(this,3,a);this.U("remotePlayerChange")}else S9(this,g.ya(this.PA,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,V9(this,"stopVideo")):Q9(this,"stopVideo");var a=P9(this);a.index=-1;a.videoId="";g.YI(a);R9(this,a);this.U("remotePlayerChange")}else S9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=P9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.A)(function(){U9("set receiver volume: "+d)},this),(0,g.A)(function(){this.bc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.A)(function(){U9("set receiver muted: "+b)},this),(0,g.A)(function(){this.bc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);Q9(this,"setVolume",e)}c.muted=b;c.volume=a;R9(this,c)}else S9(this,g.ya(this.setVolume,a,b))};
g.h.jA=function(a,b){if(1==this.g){var c=P9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Mc(b.style),g.ac(d,c.o));Q9(this,"setSubtitlesTrack",d);R9(this,c)}else S9(this,g.ya(this.jA,a,b))};
g.h.Ms=function(a,b){if(1==this.g){Q9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Lc.id});var c=P9(this);c.audioTrackId=b.Lc.id;R9(this,c)}else S9(this,g.ya(this.Ms,a,b))};
g.h.OA=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.aJ(c,a,b);R9(this,c)}Q9(this,"previous")}else S9(this,g.ya(this.OA,a,b))};
g.h.NA=function(a,b){if(1==this.g){if(a&&b){var c=P9(this);g.aJ(c,a,b);R9(this,c)}Q9(this,"next")}else S9(this,g.ya(this.NA,a,b))};
g.h.lv=function(){1==this.g?Q9(this,"dismissAutoplay"):S9(this,this.lv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}O9.O.dispose.call(this)};
g.h.P=function(){rva(this);this.B=null;this.C.clear();N9(this,null);O9.O.P.call(this)};
g.h.Ns=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.qC(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.QM=function(a,b){this.U(a,b)};
g.h.HK=function(a){if(!a)this.Bk(null),N9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=P9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)U9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,R9(this,b)}};
g.h.Bk=function(a){U9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),sva(this),this.U("remotePlayerChange")};
g.h.GK=function(a){a?(sva(this),this.U("remotePlayerChange")):this.Bk(null)};
g.h.UK=function(){var a=kva();a&&N9(this,a)};
g.h.bc=function(a){g.RH("CP",a)};
var f$=[];g.h=Eva.prototype;g.h.Hh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.Hg(d+a,b||{})};
g.h.Ls=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Jb:g.ya(this.WP,c,!0),onError:g.ya(this.VP,d),fd:g.ya(this.XP,d)};b&&(c.Ob=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.xF(a,c)};
g.h.WP=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.VP=function(a,b){a(Error("Request error: "+b.status))};
g.h.XP=function(a){a(Error("request timed out"))};
g.p(X9,g.X);X9.prototype.B=function(a){Fva(this,a.state)};
g.C(Y9,g.L);g.h=Y9.prototype;
g.h.P=function(){Y9.O.P.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.pn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.Ry,this);this.W.removeEventListener("captionschanged",this.Fy,this);this.W.removeEventListener("videoplayerreset",this.Ek,this);this.W.removeEventListener("captionssettingschanged",this.ds,this);this.W.removeEventListener("mdxautoplaycancel",this.Bu,this);this.g.unsubscribe("proxyStateChange",this.fz,this);this.g.unsubscribe("remotePlayerChange",
this.Dk,this);this.g.unsubscribe("remoteQueueChange",this.Ek,this);this.g.unsubscribe("autoplayUpNext",this.Dy,this);this.g.unsubscribe("previousNextChange",this.bz,this);this.g.unsubscribe("nowAutoplaying",this.Uy,this);this.g.unsubscribe("autoplayDismissed",this.Cy,this);this.g=this.H=null};
g.h.EB=function(a,b){2==this.g.g||(a$(this)?this.xG.apply(this,arguments):this.tG.apply(this,arguments))};
g.h.Fy=function(a){this.EB("control_subtitles_set_track",g.Tb(a)?null:a)};
g.h.ds=function(){var a=this.W.Wc("captions","track");g.Tb(a)||c$(this,a)};
g.h.tG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":d$(this,this.W.getCurrentTime());break;case "control_seek":d$(this,c[0]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Ms(b$(this),c)}};
g.h.xG=function(a,b){if(1081!=P9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":P9(this.g).qb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Mi(c[0],c[1]);break;case "control_subtitles_set_track":c$(this,c[0]);break;case "control_set_audio_track":c=c[0],a$(this)&&this.g.Ms(b$(this),c)}}};
g.h.pn=function(a){if(a$(this)){this.g.unsubscribe("remotePlayerChange",this.Dk,this);var b=Math.round(a.volume);a=!!a.muted;var c=P9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Dk,this)}};
g.h.Ry=function(){g.Tb(this.B)||Hva(this,this.B);this.C=!1};
g.h.fz=function(a,b){this.A.stop();2==b&&this.qA()};
g.h.Dk=function(){if(a$(this)){this.o.stop();var a=P9(this.g);switch(a.g){case 1081:$9(this,new g.lK(8));break;case 1:this.pA();$9(this,new g.lK(8));break;case 1083:case 3:$9(this,new g.lK(9));break;case 0:$9(this,new g.lK(2));this.F.stop();Z9(this,this.W.getVideoData().lengthSeconds);break;case 1082:$9(this,new g.lK(4));break;case 2:$9(this,new g.lK(4));Z9(this,g.$I(a));break;case -1:$9(this,new g.lK(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.U("YTP_MDX_PLAYER_ERROR")},$9(this,
new g.lK(128,a))}var a=P9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,Hva(this,a));a=P9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.Zd()==a.muted||this.G.isActive()||this.EA()}else Gva(this)};
g.h.bz=function(){this.W.U("mdxpreviousnextchange")};
g.h.Ek=function(){a$(this)||Gva(this)};
g.h.Bu=function(){this.g.lv()};
g.h.Dy=function(a){a&&(a=g.xF("/watch_queue_ajax",{method:"GET",Hc:{action_get_watch_queue_item:1,video_id:a},Jb:(0,g.A)(this.PN,this)}))&&(this.J=(0,g.A)(a.abort,a))};
g.h.PN=function(a,b){var c=new g.UQ({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.Uy=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.Cy=function(){this.W.U("mdxautoplaycanceled")};
g.h.UR=function(a,b){-1==P9(this.g).g?d$(this,a):b&&this.g.PA(a)};
g.h.EA=function(){if(a$(this)){var a=P9(this.g);this.W.removeEventListener("onVolumeChange",this.pn,this);a.muted?this.W.mute():this.W.yg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.pn,this)}};
g.h.pA=function(){this.o.stop();if(!this.g.la()){var a=P9(this.g);a.qb()&&$9(this,new g.lK(8));Z9(this,g.$I(a));this.o.start()}};
g.h.qA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};
g.C(h$,g.YV);g.h=h$.prototype;g.h.create=function(){Kva("embedded"==g.Y(this.g).g);this.D.push(g.WG("yt-remote-before-disconnect",this.DK,this));this.D.push(g.WG("yt-remote-connection-change",this.ZM,this));this.D.push(g.WG("yt-remote-receiver-availability-change",this.dz,this));this.D.push(g.WG("yt-remote-auto-connect",this.XM,this));this.D.push(g.WG("yt-remote-receiver-resumed",this.WM,this));this.dz()};
g.h.load=function(){this.g.lp();h$.O.load.call(this);this.C=new Y9(this,this.g,this.o);var a;a=(a=iva())?a.currentTime:0;var b=L9()?new O9(s9(),void 0):null;0==a&&b&&(a=g.$I(P9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));Iva(this,this.F,this.F);g.P2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.We(this.C,this.o);this.o=this.C=null;h$.O.unload.call(this);g.P2(this.g.app,5)};
g.h.P=function(){(0,g.o2)(this.D);h$.O.P.call(this)};
g.h.ll=function(a,b){this.loaded&&this.C.EB.apply(this.C,arguments)};
g.h.YF=function(){return this.loaded?this.C.suggestion:null};
g.h.Bf=function(){return this.o?P9(this.o).Bf:!1};
g.h.hasNext=function(){return this.o?P9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.yR=function(){var a=P9(this.o),b=this.g.getVideoData(),c=this.g.Dd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.F)()-a.A)/1E3:a.B;var l=1>=Zua(a)-this.getCurrentTime(),m=a.J,n=Zua(a),a=0<a.C?a.C+((0,g.F)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.zR=function(){this.o&&this.o.NA()};
g.h.AR=function(){this.o&&this.o.OA()};
g.h.DK=function(a){1==a&&(this.J=this.o?P9(this.o):null)};
g.h.ZM=function(){var a=L9()?new O9(s9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Ve(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.YA(a.videoId,g.$I(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.dz=function(){this.G=[this.A].concat(Jva());var a=e$()||this.A;i$(this,a);this.g.xa("onMdxReceiversChange")};
g.h.XM=function(){var a=e$();i$(this,a)};
g.h.WM=function(){this.B=e$()};
g.h.xR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?g$():i$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&g$(),!0):!1}};
g.h.CR=function(){Q9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ze=function(){return!1};
window._exportCheck==g.Ba&&g.u("ytmod.player.remote",h$,void 0);})(_yt_player);
